"""Generate the exact installed Linux/Python deployment dependency closure.

The portable constraints remain in ``requirements.txt``.  This command walks
only their installed dependency graph, so unrelated packages in a developer
environment cannot leak into the deployment lock.
"""

from __future__ import annotations

import argparse
import importlib.metadata as metadata
import platform
from collections import defaultdict, deque
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _root_requirements(path):
    requirements = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line or line.startswith("-r "):
            continue
        requirements.append(Requirement(line))
    return requirements


def installed_closure(roots):
    distributions = {
        canonicalize_name(item.metadata["Name"]): item
        for item in metadata.distributions()
        if item.metadata.get("Name")
    }
    requested_extras = defaultdict(set)
    queue = deque()
    for requirement in roots:
        name = canonicalize_name(requirement.name)
        requested_extras[name].update(requirement.extras)
        queue.append(name)
    visited = set()
    while queue:
        name = queue.popleft()
        if name in visited:
            continue
        visited.add(name)
        distribution = distributions.get(name)
        if distribution is None:
            raise RuntimeError("Required distribution is not installed: {}".format(name))
        environments = [""] + sorted(requested_extras[name])
        for raw_requirement in distribution.requires or ():
            requirement = Requirement(raw_requirement)
            if requirement.marker is not None and not any(
                requirement.marker.evaluate({"extra": extra}) for extra in environments
            ):
                continue
            child = canonicalize_name(requirement.name)
            before = len(requested_extras[child])
            requested_extras[child].update(requirement.extras)
            if child not in visited or len(requested_extras[child]) != before:
                queue.append(child)
    return [
        (distributions[name].metadata["Name"], distributions[name].version)
        for name in sorted(visited)
    ]


def render(rows):
    header = [
        "# Generated by scripts/generate_requirements_lock.py; do not edit manually.",
        "# Platform: {} {}".format(platform.system(), platform.machine()),
        "# Python: {}".format(platform.python_version()),
        "# Portable version ranges live in requirements.txt.",
    ]
    return "\n".join(header + ["{}=={}".format(name, version) for name, version in rows]) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--requirements", type=Path, default=PROJECT_ROOT / "requirements.txt"
    )
    parser.add_argument(
        "--output", type=Path, default=PROJECT_ROOT / "requirements.lock.txt"
    )
    args = parser.parse_args()
    content = render(installed_closure(_root_requirements(args.requirements)))
    args.output.write_text(content, encoding="utf-8", newline="\n")
    print("wrote {} pinned distributions to {}".format(len(content.splitlines()) - 4, args.output))


if __name__ == "__main__":
    main()
